name: zletter_game
description: A word puzzle game, you are challanged to form words of varying length each words last letter becomes the first letter of your next word.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.20.1
  flutter_native_splash: ^2.2.7
  cupertino_icons: ^0.1.2
  share_plus: ^4.0.10
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # change_app_package_name: ^0.1.3

flutter_native_splash:
  color: "#39393A"
  image: assets/splash.png

  android_12:
    color: "#39393A"
    image: assets/splash.png



flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: RobotoSlab
    fonts:
    - asset: fonts/RobotoSlab-Regular.ttf
  - family: RobotoSlabB
    fonts:
    - asset: fonts/RobotoSlab-Bold.ttf

  - family: Fredoka
    fonts:
    - asset: fonts/Fredoka-Regular.ttf
